CREATE TABLE IF NOT EXISTS Users (
    idUser INTEGER PRIMARY KEY NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS HighScores (
    idScore INTEGER PRIMARY KEY NOT NULL,
    score INTEGER NOT NULL,
    level INTEGER NOT NULL,
    idUser INTEGER NOT NULL,
    FOREIGN KEY (idUser)
    REFERENCES Users(idUser)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)

